[[plugins]]
repo='https://github.com/shellRaining/hlchunk.nvim'
lua_source='''
require('hlchunk').setup {
  chunk = {
    exclude_filetypes = {
      oil = true,
      gin = true,
      toml = true,
      ["gin-status"] = true,
      ["gin-log"] = true,
      ["gin-diff"] = true,
    },
    chars = {
      right_arrow = '→',
    },
    style = {
      { fg = '#ae81ff' },
      { fg = '#fc514e' }, -- this fg is used to highlight wrong chunk
    },
  },
  indent = { enable = true },
  line_num = { enable = false },
  blank = { enable = false },
}
'''
