[[plugins]]
repo='https://github.com/nvimdev/lspsaga.nvim'
depends=['nvim-web-devicons', 'nvim-treesitter']
lua_source='''
local lspsaga = require('lspsaga')
lspsaga.setup {
  ui = {
    code_action = '🚕',
  },
  lightbulb = {
    enable = false,
  },
}
local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }
local doCommand = function(cmd)
  return string.format('<Cmd>Lspsaga %s<Cr>', cmd)
end

keymap('n', ';', '<Nop>', opts)
keymap('n', ';r', doCommand('rename'), opts)
keymap('n', ';d', doCommand('peek_definition'), opts)
keymap('n', ';D', doCommand('goto_definition'), opts)
keymap('n', ';t', doCommand('peek_type_definition'), opts)
keymap('n', ';T', doCommand('goto_type_definition'), opts)
keymap('n', 'K', doCommand('hover_doc'), opts)
keymap('n', ';<Space>', doCommand('code_action'), opts)
keymap('n', ';l', doCommand('show_line_diagnostics'), opts)
keymap('n', ';j', doCommand('diagnostics_jump_next'), opts)
keymap('n', ';k', doCommand('diagnostics_jump_next'), opts)
keymap('n', ';o', doCommand('outline'), opts)
keymap({ 'n', 't' }, ';;', '<Esc><Cmd>Lspsaga term_toggle<Cr>', opts)
'''
