[[plugins]]
repo='https://github.com/echasnovski/mini.indentscope'
lua_source='''
require('mini.indentscope').setup {
  draw = {
    priority = 10,
  },
  symbol = '|',
}
'''

[[plugins]]
repo='https://github.com/echasnovski/mini.trailspace'
lua_source='''
require('mini.trailspace').setup {
  only_in_normal_buffers = false,
}
'''

