[[plugins]]
repo='https://github.com/stevearc/oil.nvim'
lua_source='''
local keymap = vim.keymap.set
local autocmd = require('utils').autocmd
require('oil').setup {}
keymap('n', '<Leader>e', '<Cmd>Oil .<Cr>', { noremap = true, silent = true })
keymap('n', '<Leader>E', '<Cmd>Oil %:p:h<Cr>', { noremap = true, silent = true })
autocmd('FileType', {
  pattern = 'oil',
  callback = function()
    vim.keymap.set('n', '<Leader>we', function()
      local oil = require('oil')
      local config = require('oil.config')
      if #config.columns == 1 then
        oil.set_columns { 'icon', 'permissions', 'size', 'mtime' }
      else
        oil.set_columns { 'icon' }
      end
    end, { noremap = true, silent = true, buffer = true })
  end,
})
'''

[[plugins]]
repo='https://github.com/nvim-tree/nvim-web-devicons'
depends='oil.nvim'
