[[plugins]]
repo='https://github.com/vim-skk/skkeleton'
depends='denops.vim'
lua_source='''
vim.api.nvim_create_autocmd('User', {
  pattern = 'DenopsPluginPost:skkeleton',
  callback = function()
    local getJisyo = function(name)
      local dictdir = vim.fn.expand(vim.fs.joinpath(require('utils').dpp_basePath, 'repos', 'github.com', 'skk-dev', 'dict', 'SKK-JISYO.'))
      return vim.fs.normalize(dictdir .. name)
    end

    vim.fn['skkeleton#config'] {
      eggLikeNewline = true,
      globalDictionaries = {
        getJisyo('L'),
        getJisyo('hukugougo'),
        getJisyo('mazegaki'),
        getJisyo('propernoun'),
        getJisyo('station'),
      },
      databasePath = '/tmp/skkeleton.sqlite3',
    }
    vim.fn['skkeleton#register_kanatable']('rom', {
      [ [[z\<Space>]] ] = { [[\u3000]], '' },
    })
  end,
})
vim.keymap.set({ 'i', 'c', 't' }, '<C-j>', '<Plug>(skkeleton-toggle)')
vim.keymap.set({ 'n' }, '<C-j>', 'i<Plug>(skkeleton-toggle)')
'''

[[plugins]]
repo='https://github.com/skk-dev/dict'
depends='skkeleton'
if=false
