[[plugins]]
repo='https://github.com/4513ECHO/treesitter-compat-highlights.nvim'
depends = 'nvim-treesitter'
lua_source='''
vim.api.nvim_create_autocmd('ColorScheme', {
  pattern = '*',
  callback = require('treesitter-compat-highlights').apply,
  desc = 'Apply compatible highlights for nvim-treesitter',
})
'''
